### ISSUE TITLE
how to install it in linux server

### ISSUE THREAD

**Issue by stroke1989** [PFPrzytycki/Differential-Mutation-Analysis#3]
Excuse me:
 I read with great interest the paper titled "Differential analysis between somatic mutation and germline variation profiles reveals cancer-related genes". Thank you for this excellent work. I want to try to use DiffMut to analyze my WES data. but I don't KNOW how to use it in linux server or how to install this software rather than the wed (I know that you develop a web version). Hope your response!

**Comment by PFPrzytycki** [comment]
Hi,

DiffMut is written in R, so to run it on a linux server the only requirement is that R be installed on the server (details here: https://cran.r-project.org/). Once R is installed, you can download the files in the GitHub directory, launch R, and type source('DifferentialMutationAnalysis.R'). At this point the commands in the ReadMe should work.
